CREATE DATABASE ecommerce;

CREATE TABLE products (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
price INT,
image VARCHAR(255)
);

CREATE TABLE orders (
id INT AUTO_INCREMENT PRIMARY KEY,
total INT,
payment_id VARCHAR(255),
order_id VARCHAR(255),
status VARCHAR(50),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);